# Generated by Django 5.2.11 on 2026-02-28 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_agent_cannedresponse_ticket_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Billing Questions'", max_length=100)),
                ('keywords', models.TextField(help_text='Comma-separated keywords: refund, money, charge')),
                ('condition', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts With')], default='contains', max_length=20)),
                ('department', models.CharField(choices=[('billing', 'Billing'), ('tech', 'Technical Support'), ('product', 'Product Support'), ('general', 'General')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_rules', to='tickets.organization')),
            ],
        ),
    ]
