# Generated by Django 5.2.11 on 2026-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_routingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='vip_threshold',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
    ]
