# Generated by Django 5.2.11 on 2026-02-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_customer_vip_threshold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cannedresponse',
            options={'ordering': ['category__name', 'title']},
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_responses', to='tickets.organization'),
        ),
        migrations.CreateModel(
            name='CannedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_categories', to='tickets.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses', to='tickets.cannedcategory'),
        ),
    ]
