# Generated by Django 5.2.11 on 2026-02-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_cannedresponse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedresponse',
            name='usage_count',
            field=models.IntegerField(default=0, help_text='How many times this template has been used'),
        ),
        migrations.AddField(
            model_name='cannedresponse',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text='List of variables used in this template'),
        ),
        migrations.AlterField(
            model_name='cannedresponse',
            name='content',
            field=models.TextField(help_text='Use {{variable}} syntax. Available: customer_name, order_number, etc.'),
        ),
        migrations.AlterUniqueTogether(
            name='cannedresponse',
            unique_together={('shortcode', 'organization')},
        ),
    ]
