# Generated by Django 5.2.11 on 2026-02-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_cannedresponse_usage_count_cannedresponse_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mentions',
            field=models.ManyToManyField(blank=True, help_text='Agents mentioned in this note using @username', related_name='mentioned_in', to='tickets.agent'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Name of the sender', max_length=100),
        ),
    ]
