# Generated by Django 5.2.11 on 2026-04-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_knowledgearticle_articlefeedback_knowledgecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file_size',
            field=models.IntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
